### ISSUE TITLE
No callback on Windows

### ISSUE THREAD

**Issue by obiwanzenobi** [bikram0000/flutter_desktop_sleep#1]
Tried setWindowSleepHandler, but cant get any event. Windows 10

**Comment by Bikram40** [comment]
have you tried the example project is it working?

**Comment by obiwanzenobi** [comment]
Very strange, the example app is working perfectly. This could be something with other plugins intercepting this event maybe. 
I'm using a few desktop-specific plugins like windowManager https://github.com/leanflutter/window_manager, launch at startup https://github.com/leanflutter/launch_at_startup, and auto updater https://github.com/leanflutter/auto_updater.
