### ISSUE TITLE
Not working with Windows 10

### ISSUE THREAD

**Issue by thisisyusub** [bikram0000/flutter_desktop_sleep#3]
I have created new app from scratch, and copied all code from your example project. It is not working as expected.
But I have copied your repo and checked your example project, it is working. What is the problem here?

Here is `flutter doctor` result:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.10, on Microsoft Windows [Version 10.0.19045.2846], locale en-US)
This is taking an unexpectedly long time...[√] Windows Version (Installed version of Windows is version 10 or higher)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.3)
[!] Android Studio (not installed)
[√] IntelliJ IDEA Community Edition (version 2023.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 2 categories.
```

**Comment by bikram0000** [comment]
due to Flutter update in win32_window.cpp file you need to change little bit of code

from here
 `HWND window = CreateWindow(
      window_class, title.c_str(), WS_OVERLAPPEDWINDOW ,
      Scale(origin.x, scale_factor), Scale(origin.y, scale_factor),
      Scale(size.width, scale_factor), Scale(size.height, scale_factor),
      nullptr, nullptr, GetModuleHandle(nullptr), this);`
To
`  HWND window = CreateWindow(
      window_class, title.c_str(), WS_OVERLAPPEDWINDOW | WS_VISIBLE,
      Scale(origin.x, scale_factor), Scale(origin.y, scale_factor),
      Scale(size.width, scale_factor), Scale(size.height, scale_factor),
      nullptr, nullptr, GetModuleHandle(nullptr), this);
`
  " | WS_VISIBLE" this need to add for listening the state.

**Comment by thisisyusub** [comment]
You are legend! Thank you very much for your help! It is working!
