### ISSUE TITLE
Question: Can we detect system ShutDown and App crash with this library?

### ISSUE THREAD

**Issue by prabhuc94** [bikram0000/flutter_desktop_sleep#6]
@bikram0000 HI, I really need your reply for this! If yes what's the keyword do i need to check?

**Comment by prabhuc94** [comment]
@bikram0000 HI, I really need your reply for this! If yes what's the keyword do i need to check?

**Comment by bikram0000** [comment]
Sorry, but this features is not available.

**Comment by prabhuc94** [comment]
@bikram0000 Is there any option to detect laptop lid closed and System in lock / unlock?

**Comment by bikram0000** [comment]
Hello,

Yes, you can detect system lock/unlock events, but it will not detect when a laptop lid is closed.

I apologize for the delayed response. I am currently occupied with other projects, so I haven't been able to maintain this plugin.

Thank you for your understanding.
