### ISSUE TITLE
Question: Is there any option to detect laptop lid closed and System in lock / unlock / Standby?

### ISSUE THREAD

**Issue by prabhuc94** [bikram0000/flutter_desktop_sleep#7]
@bikram0000 @Bikram40 Kindly give some advise on this to detect these functionalities!

**Comment by bikram0000** [comment]
Hello,

Yes, you can detect system lock/unlock events, but it will not detect when a laptop lid is closed.

I apologize for the delayed response. I am currently occupied with other projects, so I haven't been able to maintain this plugin.

Thank you for your understanding.
