### ISSUE TITLE
I need your help, of course it's paid

### ISSUE THREAD

**Issue by a121418140** [bikram0000/flutter_desktop_sleep#8]
I need to obtain FCM's encryption algorithm and Authorization: AidLogin. I hope to receive your assistance in resolving the issue for payment. May I know your contact information. I need to contact you
![96f051b4-24ad-4870-9f97-cf015f362789](https://github.com/bikram0000/flutter_desktop_sleep/assets/91479862/b61e1cd6-5d96-4b2e-be22-d5a20e9f604f)
![96f051b4-24ad-4870-9f97-cf015f362789](https://github.com/bikram0000/flutter_desktop_sleep/assets/91479862/349696d7-c30e-4056-8938-ff78104f319e)

**Comment by bikram0000** [comment]
I would be happy to help you. You can contact me through any of my social accounts: https://github.com/bikram0000#-socials
